/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 .\room_bg01.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/room_bg01.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube019.geometry} material={materials.BG} />
      <mesh geometry={nodes.pCylinder14.geometry} material={materials.BG} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.BG} />
      <mesh geometry={nodes.Cube020.geometry} material={materials.BG} />
      <mesh geometry={nodes.pCylinder15.geometry} material={materials.BG} />
      <mesh geometry={nodes.Cube3.geometry} material={materials.BG} material-color={`#${props.wallColor}`}/>
      <mesh geometry={nodes.pCylinder6.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.pCube2.geometry} material={materials.lambert8} />
      <mesh geometry={nodes.pCylinder9.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.pasted__Cylinder.geometry} material={materials.blinn4} />
      <mesh geometry={nodes.pCylinder10.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.pCylinder8.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.polySurface45.geometry} material={materials.blinn2} />
      <mesh geometry={nodes.pCylinder3.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.pCylinder7.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.pasted__Cube034.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.pCylinder5.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.pCylinder4.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.pCube1.geometry} material={materials.lambert8} />
      <mesh geometry={nodes.pasted__Cube036.geometry} material={materials.blinn4}  />
    </group>
  )
}

useGLTF.preload('/room_bg01.gltf')
