/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 .\Double.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import * as THREE from 'three'
import { useSelector } from 'react-redux'
export function Double(props) {
  
  const {fabricPath} = useSelector(state=>state.fabric.fabricType)
  const normals = useLoader(THREE.TextureLoader,fabricPath)

  const { nodes, materials } = useGLTF('/model/Double.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pTorus10.geometry} material={materials.blinn5} position={[13.45, 0, 0]} />
      <mesh geometry={nodes.pTorus4.geometry} material={materials.blinn5} position={[1.3, 0, 0]} />
      <mesh geometry={nodes.pTorus12.geometry} material={materials.blinn5} position={[12.18, 0, 0]} />
      <mesh geometry={nodes.pPlane7.geometry} material={materials.blinn6} position={[-4.2, 3.05, -9.71]} scale={0.76} > <meshStandardMaterial map={normals} /> </mesh>
      <mesh geometry={nodes.pPlane8.geometry} material={materials.blinn6} position={[6.68, 3.05, -9.71]} scale={0.76} > <meshStandardMaterial map={normals} /> </mesh>
      <mesh geometry={nodes.pTorus3.geometry} material={materials.blinn5} />
      <mesh geometry={nodes.pTorus11.geometry} material={materials.blinn5} position={[10.88, 0, 0]} />
      <mesh geometry={nodes.pTorus9.geometry} material={materials.blinn5} position={[14.73, 0, 0]} />
      <mesh geometry={nodes.pTorus5.geometry} material={materials.blinn5} position={[2.57, 0, 0]} />
      <mesh geometry={nodes.pTorus7.geometry} material={materials.blinn5} position={[5.16, 0, 0]} />
      <mesh geometry={nodes.pTorus6.geometry} material={materials.blinn5} position={[3.85, 0, 0]} />
      <mesh geometry={nodes.pTorus8.geometry} material={materials.blinn5} position={[16.04, 0, 0]} />
      <mesh geometry={nodes.polySurface196.geometry} material={materials.blinn5} />
      <mesh geometry={nodes.polySurface197.geometry} material={materials.blinn5} />
      <mesh geometry={nodes.polySurface198.geometry} material={materials.blinn5} />
    </group>
  )
}

useGLTF.preload('/Double.gltf')
