/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 .\Eyelet.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSelector } from 'react-redux'
import { useLoader } from '@react-three/fiber'
import * as THREE from 'three'

export function Eyelet(props) {

  const {fabricPath} = useSelector(state=>state.fabric.fabricType)
  const normals = useLoader(THREE.TextureLoader,fabricPath)

  const { nodes, materials } = useGLTF('/Eyelet.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface197.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface196.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface198.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface64.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface62.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface63.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface65.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface68.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface69.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface61.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface60.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface66.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface67.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface59.geometry} material={materials.eyelet_mat} > <meshStandardMaterial map={normals} /> </mesh>
      <mesh geometry={nodes.polySurface70.geometry} material={materials.eyelet_mat} > <meshStandardMaterial map={normals} /> </mesh>
      <mesh geometry={nodes.polySurface200.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface202.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface207.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface208.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface210.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface214.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface215.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface216.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface217.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface218.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface63_1.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface206.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface60_1.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface213.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface65_1.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface204.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface66_1.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface212.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface62_1.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface211.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface61_1.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface201.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface64_1.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface203.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface67_1.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface205.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface69_1.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface209.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface68_1.geometry} material={materials.blinn10} />
      <mesh geometry={nodes.polySurface219.geometry} material={materials.blinn10} />
    </group>
  )
}

useGLTF.preload('/Eyelet.gltf')
