/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 .\Goblet.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { useSelector } from 'react-redux'
import * as THREE from 'three'

export function Goblet(props) {
  const { nodes, materials } = useGLTF('/model/Goblet.gltf')

  const {fabricPath} = useSelector(state=>state.fabric.fabricType)
  const normals = useLoader(THREE.TextureLoader,fabricPath)

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pTorus8.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.pTorus9.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.pTorus10.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.polySurface196.geometry} material={materials['DoublePlate_v01:chorme']} />
      <mesh geometry={nodes.pTorus11.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.polySurface198.geometry} material={materials['DoublePlate_v01:chorme']} />
      <mesh geometry={nodes.pTorus12.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.polySurface197.geometry} material={materials['DoublePlate_v01:chorme']} />
      <mesh geometry={nodes.pTorus13.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.pTorus14.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.pTorus15.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.pTorus16.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.pTorus17.geometry} material={materials.blinn3} />
      <mesh geometry={nodes.polySurface76.geometry} material={materials.blinn4}  > <meshStandardMaterial map={normals} /> </mesh>
      <mesh geometry={nodes.polySurface199.geometry} material={materials.blinn4} >  <meshStandardMaterial map={normals} /> </mesh>
    </group>
  )
}

useGLTF.preload('/Goblet.gltf')
