/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 .\Pencil.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

import * as THREE from 'three'
import { useSelector } from 'react-redux'
import { useLoader } from '@react-three/fiber'

export function Pencil(props) {

  const {fabricPath} = useSelector(state=>state.fabric.fabricType)
  const normals = useLoader(THREE.TextureLoader,fabricPath)

  const { nodes, materials } = useGLTF('/Pencil.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface198.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.group6polySurface66.geometry} material={materials.blinn1} position={[0.01, -0.2, -0.63]} />
      <mesh geometry={nodes.group6polySurface70.geometry} material={materials.blinn1} position={[-0.67, -0.2, -0.63]} />
      <mesh geometry={nodes.group6polySurface67.geometry} material={materials.blinn1} position={[0.01, -0.2, -0.63]}  />
      <mesh geometry={nodes.group6polySurface73.geometry} material={materials.blinn1} position={[-0.67, -0.2, -0.63]}  />
      <mesh geometry={nodes.group6polySurface64.geometry} material={materials.blinn1} position={[0.01, -0.2, -0.63]}  />
      <mesh geometry={nodes.group6polySurface62.geometry} material={materials.blinn1} position={[-0.67, -0.2, -0.63]}  />
      <mesh geometry={nodes.group6polySurface71.geometry} material={materials.blinn1} position={[-0.67, -0.2, -0.63]}  />
      <mesh geometry={nodes.polySurface199.geometry} material={materials.curtain_mat} position={[-0.67, -0.2, -0.63]}  > <meshStandardMaterial map={normals} /> </mesh>
      <mesh geometry={nodes.group6polySurface65.geometry} material={materials.blinn1} position={[0.01, -0.2, -0.63]} />
      <mesh geometry={nodes.polySurface197.geometry} material={materials.blinn1}  />
      <mesh geometry={nodes.polySurface196.geometry} material={materials.blinn1} position={[-0.87, -0.2, -0.63]}  />
      <mesh geometry={nodes.group6polySurface63.geometry} material={materials.blinn1} position={[0.01, -0.2, -0.63]}  />
      <mesh geometry={nodes.group6polySurface68.geometry} material={materials.blinn1} position={[0.01, -0.2, -0.63]}  />
      <mesh geometry={nodes.group6polySurface72.geometry} material={materials.blinn1} position={[-0.67, -0.2, -0.63]}  />
      <mesh geometry={nodes.polySurface195.geometry} material={materials.curtain_mat} position={[0.01, -0.2, -0.63]}  > <meshStandardMaterial map={normals} /> </mesh>
      <mesh geometry={nodes.group6polySurface69.geometry} material={materials.blinn1} position={[-0.67, -0.2, -0.63]}  />  
    </group>
  )
}

useGLTF.preload('/Pencil.gltf')
