/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 .\Triple.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { useSelector } from 'react-redux'
import * as THREE from 'three'

export function Triple(props) {
  const { nodes, materials } = useGLTF('/model/Triple.gltf')

  const {fabricPath} = useSelector(state=>state.fabric.fabricType)
  const normals = useLoader(THREE.TextureLoader,fabricPath)

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pPlane19.geometry} material={materials.triplePleate_mat}  > <meshStandardMaterial map={normals} /> </mesh>
      <mesh geometry={nodes.pPlane20.geometry} material={materials.triplePleate_mat}  > <meshStandardMaterial map={normals} /> </mesh>
      <mesh geometry={nodes.polySurface198.geometry} material={materials.blinn11} />
      <mesh geometry={nodes.polySurface196.geometry} material={materials.blinn11} />
      <mesh geometry={nodes.polySurface197.geometry} material={materials.blinn11} />
    </group>
  )
}

useGLTF.preload('/Triple.gltf')
